quarkus.application.name=token-service
quarkus.application.version=1.0.0
quarkus.http.port=4114
quarkus.log.category."org.jboss.resteasy".level=DEBUG

#Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.devservices.show-logs=true

# Container image settings
quarkus.container-image.build=true
quarkus.container-image.group=otaku
quarkus.container-image.name=token-service

# Set global log level
quarkus.log.level=INFO

# Console logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.level=INFO

# OpenAPI and Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Token API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API for managing tokens
quarkus.smallrye-openapi.info-contact-email=jacobsmith@example.com
quarkus.smallrye-openapi.info-contact-name=Jacob Smith
quarkus.smallrye-openapi.info-contact-url=https://smithj16.github.io

# Authentication (if using security)
# quarkus.http.auth.basic=true
# quarkus.security.users.embedded.enabled=true
# quarkus.security.users.embedded.users.admin=adminpassword
# quarkus.security.users.embedded.roles.admin=admin

# Development configuration
%dev.quarkus.log.category."org.acme".level=DEBUG
%dev.quarkus.hibernate-orm.sql-load-script=import.sql

# Test configuration
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.datasource.dev-ui.allow-sql=true

# Production configuration
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://production-db:5432/quarkus_d
%prod.quarkus.datasource.username=${DATABASE_USERNAME}
%prod.quarkus.datasource.password=${DATABASE_PASSWORD}
%prod.quarkus.s3.aws.credentials.type=env
%prod.quarkus.log.console.level=WARN
%prod.quarkus.hibernate-orm.log.sql=false
%prod.quarkus.log.level=INFO

